### ISSUE TITLE
Create Front-End

### ISSUE THREAD

**Issue by SpectralPixel** [SpectralPixel/student-speaker-matcher#1]
The front-end ideally consists of:

- A text field to enter favorite subjects
- A text field to enter a list of speakers (possibly a text file if possible?)
- A button to collect the data from the text fields and dispatch the matching "algorithm" (ChatGPT)
- Loading text while the matching "algorithm" runs
- A styled text element to display the output. Could be combined with the loading text

**Comment by yetanotherparrot** [comment]
I believe this was fixed earlier today by one of @peselis's commits
